### ISSUE TITLE
Deprecation warning for `pkg_resources`

### ISSUE THREAD

**Issue by mmwinther** [statisticsnorway/kvakk-git-tools#37]
`ssb-project-cli` has `kvakk-git-tools` as a dependency. While running our unit tests I see the following warning reported:

```
.nox\unit_tests-3-10\lib\site-packages\kvakk_git_tools\ssb_gitconfig.py:27
  D:\a\ssb-project-cli\ssb-project-cli\.nox\unit_tests-3-10\lib\site-packages\kvakk_git_tools\ssb_gitconfig.py:27: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
```

The link in the warning (https://setuptools.pypa.io/en/latest/pkg_resources.html) has some information on how to migrate away from the `pkg_resources` API.

**Comment by skykanin** [comment]
I fixed this in https://github.com/statisticsnorway/kvakk-git-tools/pull/44
